export enum PageFields {
    TITLE,
    CONTENT,
    PAGE_URL,
    EXCERPT,
    META_DATA_TITLE,
    META_DATA_DESCRIPTION,
    META_DATA_CANONICAL_URL,
    TWITTER_TITLE,
    TWITTER_DESCRIPTION,
    FACEBOOK_TITLE,
    FACEBOOK_DESCRIPTION,
    CODE_INJECTION_HEADER,
    CODE_INJECTION_FOOTER
}